### ISSUE TITLE
Linker don't see inline functions

### ISSUE THREAD

**Issue by ad1Dima** [Microsoft/WinObjC#1007]
I'm trying to bridge https://github.com/sprang/Inkpad. I'm already hide Dropbox, NSUndoManager and other unimplemented references. For now I meet problem that linker don't see inline functions 

Error   LNK2001 unresolved external symbol _WDGLFillCircle  Inkpad (Inkpad\Inkpad)

How should I solve it?

**Comment by mnithish** [comment]
@ad1Dima Can you please share with is the [build log file](https://github.com/Microsoft/WinObjC/wiki/FAQ#how-do-i-get-my-project-log-file-to-help-determining-the-cause-of-an-issue)?

**Comment by ad1Dima** [comment]
@mnithish here you are
[Inkpad.txt](https://github.com/Microsoft/WinObjC/files/475961/Inkpad.txt)

**Comment by mnithish** [comment]
@ad1Dima Thanks. It looks like our compiler defaults inline functions to static. To unblock yourself I would recommend adding an "extern" keyword to the inline functions in the source file for WINOBJC. I am following up with the compiler guys to see if we can find a permanent solution

#ifdef WINOBJC
extern
#endif
inline void WDGLFillCircle(CGPoint center, float radius, int sides)

**Comment by ad1Dima** [comment]
thanks, It was helpful
Had to replace static inline with extern inline too
#ifdef WINOBJC
extern
#else
static
#endif
inline float WDMagnitude(CGPoint point)

**Comment by ad1Dima** [comment]
And what about permanent solution in compiler?

**Comment by ad1Dima** [comment]
@weswmsft @mnithish any news from compiler team?

**Comment by weswmsft** [comment]
Here is the explanation from the compiler team:


Clang/C2 is supposed to follow what CL does. In both cases, I’m not seeing inline functions marked as static in my test. However, if the function is marked inline, we are not required to emit it. If we do decide to emit it, it will be extern select any (so the linker will just pick any one of the versions of the inline function from one of the translation units).

This means that an inline function should be defined everywhere it is used (or an extern one should be available). It seems like the open source code mentioned in the bug is using inline in an incorrect way.

“A function where all the declarations (including the definition) mention inline and never extern. There must be a definition in the same translation unit. The standard refers to this as an inline definition. No stand-alone object code is emitted, so this definition can't be called from another translation unit.”

http://www.greenend.org.uk/rjk/tech/inline.html
http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1570.pdf

“Second, in case of raw inline (ie without static or extern) to provide an inline definition as an alternative to an external one, which has to be present in a different translation unit. Not providing the external one is undefined behaviour, which will normally manifest as linking failure.”

http://stackoverflow.com/questions/16245521/c99-inline-function-in-c-file/16245669
