### ISSUE TITLE
UIScrollView:  contentInset causes postion to offset after first pan/zoom

### ISSUE THREAD

**Issue by pittmab** [Microsoft/WinObjC#1096]
We set the contentInset property on UIScrollView.  The scroll view is looking at the document correctly until we do a pan/zoom.  Then we pop to the contentInset and have to pan to get back to where we started.

**Comment by yiyang-msft** [comment]
Hi, 
  I am trying to understand the issue here. would you mind giving me a little more info on your repro. It would be great if you can give me some more info. 
  1. what is the contentInset config on your UIScrollview view? 
  2. when you do pan/zoom. what do you mean by " we pop to the contentInset and have to pan to get back to where we started. "?

**Comment by pittmab** [comment]
Adding a debug log when debug_all is set to true in UIScrollView.
[output.txt](https://github.com/Microsoft/WinObjC/files/590966/output.txt)

**Comment by yiyang-msft** [comment]
I can not repro this issue, please re-activate this issue if you have a repro.
