### ISSUE TITLE
WOCCatalog asserts in Accelerate 2 on debug builds

### ISSUE THREAD

**Issue by kellymor** [Microsoft/WinObjC#1261]
Using the WOCCatalog sample, if I build it for the debug configuration and select the Accelerate 2 item in the main view, the app asserts.  On a device the app closes unexpectedly.

**Comment by rajsesh-msft** [comment]
This is by design.  vImageCreateCGImageFromBuffer() allocates the data used by the buffer, using malloc.  The caller is expected to free it using free().  Unfortunately, with retail build of the SDK and debug build of woccatalog, this will result in heap mismatch causing the assert.  This is not a new issue.

**Comment by rajsesh-msft** [comment]
@bviglietta correctly pointed out that vimage library should be using IwMalloc/IwFree instead and everything will auto-magically work.
