### ISSUE TITLE
vsimporter crashes

### ISSUE THREAD

**Issue by gabrielmaldi** [Microsoft/WinObjC#13]
When I run `vsimporter` with `-loglevel debug` all I get before the crash is: `[W] Ignoring unsupported PBXHeadersBuildPhase in "Plugins" target.` I'm running version `1.0 (2627d23)`.

Unfortunately I can't share my Xcode project. Is there a way to get more information to diagnose?

Thanks!

**Comment by asimonov-msft** [comment]
I will try to add more logging to the tool in the future. In the meantime, the fastest way for you to diagnose the problem would be to build vsimporter yourself and see where it crashes.

If you did not perform a recursive clone of the WinObjC repository, you will need to initialize a few submodules required by vsimporter. To do so, run the following commands in a Git Bash window:
```
git submodule update --init tools/vsimporter/third-party/sole
git submodule update --init --recursive tools/vsimporter/third-party/PlistCpp
```

To generate a Visual Studio solution for building vsimporter, run the following commands in a Command Prompt window (requires [cmake](http://www.cmake.org/download/) to be installed):
```
mkdir tools\vsimporter\build
cd tools\vsimporter\build
cmake ..
explorer .
```

To build and run the tool:
  1. Open VSImporter.sln.
  2. Right-click on the vsimporter project, and select Set as StartUp Project
  3. Right-click on the vsimporter project again, select Properties -> Configuration Properties -> Debugging and customize the Command Arguments and/or Working Directory. At the very least you will need to specify the SDK location (I would recommend using a pre-packaged version of the WinObjC SDK) and the location of your Xcode project.
  4. Build and run the tool to see where it fails.

**Comment by triplef** [comment]
I have the exact same issue, crashing after the same log message. I’ve run it in the debugger as suggested and from what I can tell it seems to be caused by `SBBuildPhase::create()` calling `SBFrameworksBuildPhase::create()` with a NULL `phase` parameter in this code (see also screenshot below):

```c++
  // Force creation of a PBXFrameworksBuildPhase and/or PBXResourcesBuildPhase,
  // if they were not created explicitly.
  if (sourcesPhase && !frameworksPhase)
    ret.push_back(SBFrameworksBuildPhase::create(NULL, parentTarget));
  if (sourcesPhase && !resourcesPhase)
    ret.push_back(SBResourcesBuildPhase::create(NULL, parentTarget));
```

Simply returning in `SBFrameworksBuildPhase::SBFrameworksBuildPhase()` and `SBFrameworksBuildPhase::writeVCProjectFiles` when `m_phase` is NULL allowed the import to complete for me, but I’m not sure if that’s the right way to fix this...

Let me know if you need more info.

![screenshot 2015-08-28 15 12 59](https://cloud.githubusercontent.com/assets/6037/9547054/d9dcd458-4d97-11e5-9d32-4c8238343217.png)

**Comment by gabrielmaldi** [comment]
@triplef thank you for your help. @asimonov-msft I've been snowed under with work and haven't had a chance to dig into this. Do close this issue when that commit is merged.
