### ISSUE TITLE
_cmd is not being set as expected.

### ISSUE THREAD

**Issue by edvv** [Microsoft/WinObjC#1311]
Dear WinObjC Engineers,

The attached project (selerror.zip) is a simple unit test showing how _cmd is not being set as expected. The file selerror.txt in the zip shows the output for macOS and Windows; specifically on macOS _cmd is equal to the selector of the same method signature ("** Selector IDs are equal" is printed in the output) whereas on Windows it is not (the string is not logged).

Sincerely,

Ed

[selerror.zip](https://github.com/Microsoft/WinObjC/files/568716/selerror.zip)

**Comment by DHowett-MSFT** [comment]
@edvv Thanks for the report.

The Objective-C runtime provides `sel_isEqual` for selector comparison. Since selectors can be emitted in different modules and transformed at runtime, `==` comparison for `SEL` is ill-formed.

That having been said, it probably works differently on WinObjC due to *type-dependent dispatch*. A selector with a type encoding (which you'd see emitted for a method body) is pointer-inequal to a selector without one (the sort that is emitted via `@selector(...)` syntax).

```objc
- (void)hello:(int)arg {
}
... @selector(hello:) ...
```

effectively emits:

```objc
struct SEL $hello$t = {
    "hello:",
    "v12@0:4i8"
};

struct SEL $hello$u = {
    "hello:",
    NULL
};
```

and a comparison between them equates to `&$hello$i == &$hello$u`.

**Comment by edvv** [comment]
@DHowett-MSFT FYI:

https://developer.apple.com/reference/objectivec/1418736-sel_isequal?language=objc

Discussion
sel_isEqual is equivalent to ==.

== is often used in a lot of code to test action variables, see for example:

https://developer.apple.com/reference/objectivec/nsobject/1518160-validatemenuitem?language=objc

This appears to be an incompatability between iOS Obj-C and winobjc.

**Comment by bbowman** [comment]
@DHowett-MSFT would there be anything we could do with operator overloading in C++ environments to get the behavior @edvv is requesting here? Might be an easy-ish first step?

**Comment by edvv** [comment]
@bbowman FYI: I've already converted the codebase here to only use sel_isEqual() which is working well, so I no longer need the fix (no hurry on my part). It might be a good idea to document this issue for other people though. Whether selectors should be typed, and what to do about it long term, is another matter.

**Comment by DHowett-MSFT** [comment]
Closing this as resolved/won'tfix. We'll rely on the Reference Platform documentation for sel_isEqual and selector comparison here. :smile:
