### ISSUE TITLE
working with VS Studio 2017? Obj-C?

### ISSUE THREAD

**Issue by JMccormick264** [Microsoft/WinObjC#1590]
How do I get this working with Visual Studio 2017? I tried using the the vsix objective-c-syntax highlighting file but it won't work with Visual Studio 2017. Can someone help?

**Comment by antoine-haas** [comment]
Hello @Legitgamer264,
WinObjC does not yet officially support VS 2017 since it's final version has not been released (only a release candidate is currently available). In the meantime, you can still use VS 2017 RC with WinObjC projects without the vsix if you want since most of its features have been moved to VS 2017 itself. 

Once the vsix is available for VS 2017 we'll let you know.

**Comment by weswmsft** [comment]
VS2017 is now supported
