### ISSUE TITLE
Canabalt - about screen text is blurry 

### ISSUE THREAD

**Issue by ashvarma** [Microsoft/WinObjC#1594]
master build: 20161213.2 
flavor: x86

I compared it with an image from build 20160923.1 and we've regressed this. 
Images attached. 

![canabalt_aboutscreen_20160923 1drop](https://cloud.githubusercontent.com/assets/13685945/21367498/2f6fc91c-c6b3-11e6-8f20-06c2a07dc4a4.PNG)
![canabalt_aboutscreen_20161213 2drop](https://cloud.githubusercontent.com/assets/13685945/21367497/2f640bc2-c6b3-11e6-854d-1dd363a9ae9f.PNG)

**Comment by ms-jihua** [comment]
Looks like we're somehow handling line-wrapping incorrectly, as the blurriness only occurs on certain lines (seems to be independent of line breaks, as "The original..." and "Eric..." both take place after \n\n. The bottom section is entirely individual lines)

Interesting that the blur is only vertical. Wonder if this means that we've got an incorrectly-calculated offset somewhere...

**Comment by ms-jihua** [comment]
It looks like the issue is that we don't handle floating point offsets well. The line offsets are calculated in Canabalt itself, so they are not incorrect, but they are usually non-integral floats (14.0002, 42.50001).

Flooring the x- and y-offsets to make them integral gets rid of the blur.
![image](https://cloud.githubusercontent.com/assets/16024095/21571805/a6cc8564-ce87-11e6-9ce6-c865e32469f6.png)

However, setting x- and y-offsets to their floor() + 0.5 reproduces the blur in both vertical and horizontal directions!
![image](https://cloud.githubusercontent.com/assets/16024095/21571904/a5f4024c-ce88-11e6-9816-3f2608dc258b.png)

I'm suspecting that this has to do with us using a bitmap for our render context ( @DHowett-MSFT can you comment on this? ), causing this interpolation artifact when our offsets aren't integral. It's particularly noticeable in this case because of the pixelated style of font Canabalt uses.
