### ISSUE TITLE
BitmapFormats tests are incorrect and might not validate the results due to uninitialized for loop controller. 

### ISSUE THREAD

**Issue by msft-Jeyaram** [Microsoft/WinObjC#1694]
The values passed to the bitmapcontextCreate are incorrect and 

The main loop validate code has an uninitialized indexer.

` for (size_t i; i < data.size(); ++i)`

this led to some interesting cases :(

**Comment by DHowett-MSFT** [comment]
I wrote such a bad test!

**Comment by DHowett-MSFT** [comment]
* Bitmap context is initialized with 0xABABABAB.
* We draw with alpha into it.
* We enumerate its bytes with an uninitialized counter, occasionally passing the test because `(garbage) > bytes.size()`
* We do not properly calculate the number of bytes per pixel (it should be `pow(2, (bpp >> 3) - 1)`) (because `pow(2, 0) == 1` for 8bpp)
* On top of all that, the Alpha None tests might even be getting premultiplied THANKS D2D

**Comment by DHowett-MSFT** [comment]
Fixed.
