### ISSUE TITLE
Install Missing features does nothing

### ISSUE THREAD

**Issue by mlfarrell** [Microsoft/WinObjC#17]
I get a box that says I need to install Universal Windows Platform Tools to load the sample project, after clicking "install" nothing happens....

any ideas?

**Comment by jmsaunders-ms** [comment]
We've seen problems with installing the platform tools before.

You can try adding the feature through the Add/Remove Programs section in the Control Panel, modifying Visual Studio.

We don't control this part of the project though and I'm not sure there is much we can do about Visual Studio installation problems, sadly. You can file a bug at https://connect.microsoft.com/visualstudio if the problem persists.

If anyone else is seeing this problem and can give details about their installation, it might prove helpful, especially if they have since fixed the problem.

**Comment by mlfarrell** [comment]
Thanks for the rapid response.  I will try that.  I may have to link more VS content to my Z: however since C: is once again down to its last 2 GB.

You guys are awesome for open sourcing this btw.

**Comment by MatthewCarven** [comment]
Any resolution on this? I'm using VS2017 and the project I open requires WPF amongst other things, the installer pops up, ask permission to close VS2017, runs through its install procedure and then returns me to the same project which reports project unloaded and the only option is to "install missing features"?

Is there anything I can check? A log file or sumfin?
