### ISSUE TITLE
CoreGraphics Unit tests are failing on ARM.

### ISSUE THREAD

**Issue by pradipd** [Microsoft/WinObjC#1772]
The following CoreGraphics Unit tests are failing on ARM.
CTFrame.BasicUnicodeTest
CTFontManager.DrawWithCustomFont 
CTFont.DrawGlyphs
TestDrawingTextInFonts/Fonts.TestFonts/3

**Comment by aballway** [comment]
CTFontManager.DrawWithCustomFont, CTFont.DrawGlyphs, and TestDrawingTextInFonts/Fonts.TestFonts/3 are all failing due to slight drawing differences, and can be fixed by adding a small margin for error.  CTFrame.BasicUnicodeTest fails because arms seems to render Gurmukhi and Traditional Chinese Script slightly differently than on x86/before.  This causes a significant drawing difference because the lines are broken in a different place, so a margin for error could be to great for a reasonable test, so I think the best course of action would be to remove the glyphs causing the issue and keep testing Unicode support with glyphs that have remained stable
