### ISSUE TITLE
vsimporter.exe ignores linker search path argument

### ISSUE THREAD

**Issue by edvv** [Microsoft/WinObjC#1835]
Dear WinObjC Engineers,

vsimporter.exe ignores Xcode's Linking > Other Linker Flags and Search Paths > Library Search Paths fields so that the linker -L argument (its analog) is not translated to the Visual Studio linker arguments.

Sincerely,

Ed

**Comment by weswmsft** [comment]
Current VsImporter ignores LIB search paths on purposes because the likelihood of finding Windows libraries there is almost zero.

Therefore this will only be useful if the Xcode search paths somehow contain a Windows library (since we obviously can’t link against any iOS libs).

Importing Xcode library search paths could be helpful for developers that are willing to customize their Xcode projects to make the import/reimport easier.

This is certainly an interesting idea and a “nice to have” feature but given the work around we won't be implementing this right now.

**Comment by edvv** [comment]
> Therefore this will only be useful if the Xcode search paths somehow contain a Windows library

... that is exactly the use case at hand.

> Importing Xcode library search paths could be helpful for developers that are willing to customize their Xcode projects to make the import/reimport easier.

... that is the reason for the issue. Right now, each reimport requires the manual adjustment of the linker line.
