### ISSUE TITLE
Are pods supported?

### ISSUE THREAD

**Issue by Romascu** [Microsoft/WinObjC#2005]
Are podfiles supported? I read the page about third-party library support and saw what third-party libs are supported, i was also wondering if native libs (native pods) are supported 100%...libraries that only use the iOS API's i mean.

Thanks in advance.

**Comment by antoine-haas** [comment]
Hello @Romascu,

Support for pods/libs depend on which pod you are using. WinObjC currently only supports open source pods from which you can add source files directly to your project (this is because they need to be recompiled to Windows 10 compatible binaries). As a result, compatibility depends on WinObjC's API coverage for the ones used by the pod. The best way to evaluate the current compatibility of the SDK with a given pod is to submit your app that includes the sources for the pod to the [app analysis tool](https://developer.microsoft.com/en-us/windows/bridges/ios/app-analyzer-tool) which will give you a compatibility report.

**Comment by weswmsft** [comment]
podfiles are not supported and will likely not be supported in the future.
