### ISSUE TITLE
[x86] CGCatalog - various rendering issues 

### ISSUE THREAD

**Issue by ashvarma** [Microsoft/WinObjC#2152]
With the latest master build - 20170228.1

Set line width = 5.0

CGPathAllElipse - bottom of the ellipse and rectangle seem cropped 

Looking at the rest of the Paths – in some places the vertices are aligned and others they aren’t. 

For CGPathAddRoundedRech the Image doesn’t match the comparison image. This is true for Line Width = 2.0 as well

**Comment by DHowett-MSFT** [comment]
I think at 5.0, the vertex misalignment and clipping are is expected. The label has a white background, and I can reproduce this from all the way before the CGD2D merge.

@henryfox It looks like rounded rects are broke as. Did we have collateral in CoreGraphics.Drawing to catchy this?

**Comment by DHowett-MSFT** [comment]
![image](https://cloud.githubusercontent.com/assets/14316954/23567747/a1e89464-000c-11e7-9524-e33d35553a5c.png)

**Comment by MSFTFox** [comment]
We don't have regression testing for the AddRoundedRects API. It looks like the problem is in how a D2D1 geometry is added to our customized GeometrySink. Our custom geometry sink makes the assumption that a geometry being added is not a completed geometry in the sense that it assumes the geometry doesn't rely on an EndFigure call to complete the shape. Rounded rects in D2D are created with 4 arc segments, 3 straight lines, and an EndFigure call while our custom geometry sink ignores any EndFigure call that we haven't explicitly made in CG as a part of our figure tracking work. I'm working on a solution to this which most simply will be enabling full functionality of Simplifying into the custom geometry sink for certain scenarios that we will turn on and off in CoreGraphics if and only if we are expecting D2D to rely on these calls. I've also added this case to the CoreGraphics.drawing tests as a part of this.
