### ISSUE TITLE
[Packaging] WinObjC Packaging package does not get the correct package version string.

### ISSUE THREAD

**Issue by mukhole** [Microsoft/WinObjC#2276]
SetPackageVersion depends on a property instead of the actual task GetPackageVersion, because of which some package strings (major version etc.) are not set and we do not get the correct package version string.

**Comment by bbowman** [comment]
Assigning to @memontic-ms to investigate. As we've discussed before, we shouldn't be overly ambitious with what we do for people automatically since we can't know everything about our consumer (do they use git, do they use GitFlow, do they have remotely the same versioning scheme etc).

I'm thinking what we should do is provide a file that has the SetPackageVersion target for them but it is empty except for a commented out version that does our stuff with instructions of what is needed if they want to uncomment it?

**Comment by memontic-ms** [comment]
WinObjC.Packaging no longer provides automatic package version string as of #2294/[aec9381](https://github.com/Microsoft/WinObjC/commit/aec9381a1e6f4a3be550e1bf508e5775cf6c01c8).
Closing since the "bug" part of this issue no longer exists.  

We can open a task to get automatic versioning back into WinObjC.Packaging if there is need for it. First we need to get our own package versioning ironed out.
