### ISSUE TITLE
[Packaging] WinObjC Packaging package does not correctly set the include paths for the package consumers

### ISSUE THREAD

**Issue by mukhole** [Microsoft/WinObjC#2277]
The props file (for consumers) is using InternalSystemIncludePaths, it should be using UserIncludes or AdditionalIncludes instead.

**Comment by bbowman** [comment]
Assigning to @memontic-ms to investigate. The Packaging package shouldn't be using SystemIncludePaths because it logically doesn't map to system components. If/When we move build.sln to use the packaging package we may want this to be configurable.

@mukhole I'll follow up with you on this but either one should theoretically work with different implications to the compiler. I'm surprised it totally didn't work?

**Comment by memontic-ms** [comment]
Right now we have this coming in with the default props:
```
  <ItemDefinitionGroup>
    <ClangCompile>
      <InternalSystemIncludePaths>$(MSBuildThisFileDirectory)\include\;%(InternalSystemIncludePaths);</InternalSystemIncludePaths>
    </ClangCompile>
  </ItemDefinitionGroup>
```

Looking at our WinRTSample, we're specifying -MMD which will set "Use System Headers For Dependencies" as No. Our defaults props for the include paths (above) aren't doing anything.
