### ISSUE TITLE
Targets with BeforeTargets="Build" never get executed.

### ISSUE THREAD

**Issue by mukhole** [Microsoft/WinObjC#2302]
A simple example is:
<Target Name="_ErrWhenExecuted" **BeforeTargets="Build**">
      <Error Text="This never gets executed." />
  </Target>

Add this to any of the Islandwood vcxproj files, and compile it. The target never gets executed.

But **BeforeTargets="_ClangCompile**" works.

**Comment by memontic-ms** [comment]
I added the following target to a vcxproj in tools.sln, build.sln, and WOCCatalog-WinStore10.sln. The error text definitely was produced in each build. However, when the error tag was not present, sometimes the msbuild output did not say it was running the target (probably because the target did nothing).
```
  <Target Name="_ErrWhenExecuted" BeforeTargets="Build">
    <Error Text="Target: _ErrWhenExecuted" />
  </Target>
```

Also, to execute before Build, I believe it's recommended to override the BeforeBuild target instead. 
[https://msdn.microsoft.com/en-us/library/ms366724.aspx](https://msdn.microsoft.com/en-us/library/ms366724.aspx) 

I can't find a fault in execution because of this issue. Closing.
