### ISSUE TITLE
Visual Studio 2017 fail - Nuget

### ISSUE THREAD

**Issue by chiefgreek** [Microsoft/WinObjC#2390]
I can no longer load my ios converted project in Visual Studio 2017.
I use the winobjc from chocolatey and get this error on load

Unable to resolve WinObjC.Frameworks  for UAP,Version=v10.0.
Unable to resolve WinObjC.Language  for UAP,Version=v10.0.

Any ideas?

**Comment by bbowman** [comment]
@chiefgreek Thank you for trying out the new packaging stuff!

I believe the issue you are hitting is because we have not released a stable (**master**) package yet (we are currently in the process of building and validating a new master release).  In your project.json you can make the following changes for now to pick up our latest daily builds for this next release. After we release the stable package, please change back to `"*"` to get the stable packages.  

**NOTE:** You can also make these changes in the Nuget Package Manager by right clicking on the solution and selecting "Manage NuGet Packages for Solution". It should show you latest versions of our packages so you can update.

```diff
{
  "dependencies": {
-    "WinObjC.Frameworks": "*",
-    "WinObjC.Language": "*"
+    "WinObjC.Frameworks": "0.2.170229-dev-*",
+    "WinObjC.Language": "0.2.170229-dev-*"
  },
  "frameworks": {
    "uap10.0": {
      "imports": "native"
    }
  },
  "runtimes": {
    "win10-arm": {},
    "win10-x86": {},
    "win10-arm-aot": {},
    "win10-x86-aot": {}
  }
}
```

I'm going to close this issue but please re-open it if this doesn't fix your problem. I very much want our packaging story to be as seamless as possible for you guys.
