### ISSUE TITLE
Symbols are missing/not indexed properly for many binaries built in build.sln

### ISSUE THREAD

**Issue by pradipd** [Microsoft/WinObjC#2417]
While investigating a dump with Ashwini, we noticed that symbols were missing for many of the binaries produced in build.sln.   E.g.
Foundation
CoreFoundation
CoreGraphics
AVFoundation
ImageIO 

After looking at the build logs and the symbol server index, it looks like we are doing the following in the build.
1. Build foundation.dll/pdb
2. Put it in package
3. Re-build foundation.dll/pdb <-- I don't think we should be doing this.
4. Indexing the foundation.dll/pdb created in step 3 instead of step 1.

Thus, the symbol server has all the symbols for binaries created in step 3, but that is not what is in the package.

**Comment by DHowett-MSFT** [comment]
@MSFTFox was seeing this during some debugging scenarios as well.

**Comment by MSFTFox** [comment]
I was seeing something similar. Working with one of our sample apps, I was building for debug but the pdb's were not matching. It turns out in my case that it was grabbing the package for the release build I had from a good while back instead of the debug builds. Once I cleared out the release folder and did nuget restore it was fine.

Ultimately this isn't the same thing I was seeing and talking with @memontic-ms it seems this is intended. As for rebuilding the pdb's again instead of using the one packaged, I'm not sure. I didn't see any issues but that does seem like an extra/incorrect step.
