### ISSUE TITLE
 CGGradientCreateWithColors() does not support null colorspace

### ISSUE THREAD

**Issue by steventroughtonsmith** [Microsoft/WinObjC#2472]
CGGradientCreateWithColors crashes in CoreGraphics if passed a null value for the colorspace. On iOS, this does not happen — null is an acceptable value for the colorspace paramater.

This affects third-party design tools like PaintCode, which emit code with no specified colorspace.

```
//// Color Declarations
UIColor* glossGradientColor = [UIColor colorWithRed: 1 green: 1 blue: 1 alpha: 0.5];
UIColor* glossGradientColor2 = [UIColor colorWithRed: 0.628 green: 0.628 blue: 0.628 alpha: 0];
	
//// Gradient Declarations
CGFloat glossGradientLocations[] = {0, 1};
CGGradientRef glossGradient = CGGradientCreateWithColors(NULL, (__bridge CFArrayRef)@[(id)glossGradientColor2.CGColor, (id)glossGradientColor.CGColor], glossGradientLocations);
```

**Comment by msft-Jeyaram** [comment]
@steventroughtonsmith  Currently CGGradientCreateWithColors is returning NULL if CGGradientCreateWithColors::colorSpace is null. so the crash might be due to some other code attempting to access null.
Sadly these are some of the undocumented behaviours that ios have. I am sending out a fix soon to address this.

Thank you for reporting your finding 😃

**Comment by msft-Jeyaram** [comment]
Further investigation reveals the support is only for CGGradientCreateWithColors, while CGGradientCreateWithColorComponents with a null colorspace will return NULL on the ref platform.
