### ISSUE TITLE
Cannot install winobjc-tools via chocolatey

### ISSUE THREAD

**Issue by mattmunich** [Microsoft/WinObjC#2507]
Using an elevated powershell, yields the following results:

https://www.screencast.com/t/A9DQSsX11m

and

https://www.screencast.com/t/5dd0rPbkg64

Tried on another computer which had VS2017 Enterprise installed.  It installed fine using the command `choco upgrade winobjc-tools -pre`.  This did not work  `choco upgrade winobjc-tools`

Perhaps some tweaks to the readme are in order? Is it something about VS2017 community edition?

**Comment by bbowman** [comment]
@mattmunich unfortunately our stable package is in moderation right now (https://chocolatey.org/packages/winobjc-tools/0.2.170407) and until that is done you won't be able to see it with the normal commands. Use --pre for now

In terms of the machine differences, looks like you are getting:
ExtensionManager.NestedExtensionInstallException

Which I'll have to dig into more. Did you happen to have already installed any winobjc VSIXs?

**Comment by bbowman** [comment]
@DHowett-MSFT was able to repo locally and we found out the issue is related to the nugetizer VSIX that we try to install. I have opened https://github.com/NuGet/Home/issues/5026 on them. 

@mattmunich, You can workaround the issue for now by installing the xamarin tools (Mobile development with .NET workflow option) and trying again.

I will investigate other workarounds for our install script in new versions of the tools package.

**Comment by mattmunich** [comment]
> Did you happen to have already installed any winobjc VSIXs?

Neither laptop (community or enterprise).  I am now installing the Xamarin Tooling on my community laptop and will report back later.

**Comment by bbowman** [comment]
Updated the readme. Please reopen if you are still having issues.
