### ISSUE TITLE
hstrToNSStr should return a @"" instead of nil if the HSTRING is null.

### ISSUE THREAD

**Issue by pradipd** [Microsoft/WinObjC#2534]

**Comment by pradipd** [comment]
static NSString* hstrToNSStr(HSTRING str, bool free = false) {
    if (WindowsIsStringEmpty(str))
        return nil;  <-- @"" would be better than nil.

**Comment by DHowett-MSFT** [comment]
Why, though? An NSString reference being nil is a strong indicator that the source data does not exist; isn't that the same as a NULL HSTRING?

**Comment by bbowman** [comment]
Yeah I don't know that I agree. What situation is this failing in? Should we have it default to the existing behavior but be plugable for your situation?

**Comment by DHowett-MSFT** [comment]
FWIW, a `nil` string is fundamentally identical to `@""` for Objective-C consumers.

**Comment by bviglietta** [comment]
In WinRT there's no distinction between an empty string and a null string. This makes it unclear how to translate results to Objective-C, where there's a mild distinction between empty strings and null strings.

For what it's worth, I think returning @"" instead of nil is better, more closely matching the semantics of the underlying WinRT result.

**Comment by rajsesh-msft** [comment]
Pending any actual scenarios that require this distinction, resolving this.
