### ISSUE TITLE
setting IsThumbToolTipEnabled

### ISSUE THREAD

**Issue by esa-h** [Microsoft/WinObjC#2589]
How to access / change Slider Class properties that are not in the iOS sliders? I would like to set the IsThumbToolTipEnabled to false. Or alternatively I would like to use ThumbToolTipValueConverter. My problem is that some of my sliders should only show integer values or no values at all in the thumbtooltips.

**Comment by yiyang-msft** [comment]
Hi, @esa-h 

  To disable IsThumbToolTipEnabled yourself, you can utilize one of extensions property that is provided in UIView.h.  We will evaluate and consider changing this to default in the future. 

// WinObjC Xaml Extensions
@interface UIView (UIKitXamlExtensions)
+ (RTObject*)createXamlElement;
- (instancetype)initWithFrame:(CGRect)frame xamlElement:(RTObject*)xamlElement;

// To use this object, it must be cast to the appropriate type using rt_dynamic_cast,
// like so:
//   RTObject* rtobj = [myUITextField xamlElement];
//   WXCTextBox* xamlTextBox = rt_dynamic_cast<WXCTextBox*>(rtobj);
//   NSLog(@"The text is %@", xamlTextBox.text);
@property (nonatomic, readonly, strong) RTObject* xamlElement;

@end

So in your case, you can disable the tooltip by do this. 
   RTObject* rtobj = [myUISlider xamlElement];
   WXCSlider* xamlSlider  = rt_dynamic_cast<WXCSlider*>(rtobj);
   xamlSlider.isThumbToolTipEnabled = NO;


For your root problem - "My problem is that some of my sliders should only show integer values or no values at all in the thumbtooltips", can you give us the your config of your sliders - e.g., min/Max range etc and its bounds, so that we can repro it and trying to fix them in our side? 

Thanks

**Comment by esa-h** [comment]
Hello @yiyang-msft , thank you for your answer but I was not able to hide the thumbtooltip. An example project would be great.

I think that hiding the thumbtooltip could be a good idea as iOS apps don't have thumbtooltips and apps already use some way to tell the user the value of the slider.
In my case some integer sliders can have min value of 1 and max value 100 and some min value 1 and max value 10,000. If I could hide the thumbtooltip that would be all I would need.

**Comment by yiyang-msft** [comment]
@esa-h, 

  as part of  #2706, i disabled the tooltip on UISlider. so once we publish it master on next release, you will get it for free. Hope this helps.

Thanks
Yi

**Comment by esa-h** [comment]
Yes, that would be great. Thank you!
