### ISSUE TITLE
unrecognized token

### ISSUE THREAD

**Issue by 150up** [Microsoft/WinObjC#260]
unrecognized token on Objective-C keywords such as property, #import, etc..

**Comment by cridlig** [comment]
Same issue with Objective C header files

**Comment by antoine-haas** [comment]
Could you share more details so that we can repro the issue, like the exact error messages you're receiving and the code that originated them?

**Comment by cridlig** [comment]
See attached screenshot

![screenshot 1](https://cloud.githubusercontent.com/assets/4505679/12561576/cabfdd4c-c355-11e5-8d66-28ce591a5784.png)

**Comment by antoine-haas** [comment]
Thank you for the clarification. These errors happen in .h files because the current parser cannot properly differentiate C++ .h files from Objective-C .h files. However, those shouldn't generate compiler errors and you should be able to build your app. As a result, this will be fixed on the long term but is not in our immediate roadmap.

**Comment by antoine-haas** [comment]
This is now addressed in the [FAQ](https://github.com/Microsoft/WinObjC/wiki/FAQ#intelliSenseErrorAnchor) of the wiki.
