### ISSUE TITLE
Cocos2d-x project didn't compile

### ISSUE THREAD

**Issue by petriw** [Microsoft/WinObjC#274]
I tried to create a new Cocos2d-x project, and it didn't compile. My issue was that it could not compile the Cocos2d-h library.

1) Created a new Cocos2d-x project on my mac, it compiles and works
2) Ran it through vsimporter
3) Project not compiling, Cocoa not found, and issues with OpenGL.

Source:
https://onedrive.live.com/?cid=733e3ffab634ec2c&id=733E3FFAB634EC2C%21888175&authkey=%21AJ6wM6U8kJBwe9Q

**Comment by SaeedAkhter-MSFT** [comment]
Hi petriw,

Can you help me understand your requirements around Cocos2d-x?  Since Cocos2d-x is C++ my expectation was that developers would use the work contributed by Microsoft Open Technologies for porting to Windows:
https://msopentech.com/opentech-projects/cocos2d-x-windows-devices/
https://msopentech.com/blog/2015/05/04/cocos2d-x-3-6-is-here-modern-windows-support-too/

For WinObjC, we recently started evaluating https://github.com/cocos2d/cocos2d-objc to identify work that would improve our compatibility with that framework.  That would allow games written in Objective-C using Cocos2d-ObjC to port to Windows.

Thanks,
Saeed

**Comment by RustyMoyher** [comment]
Hi Saeed,

On a similar note, I'm looking at getting several projects working with https://github.com/cocos2d/cocos2d-iphone-classic

This repo is version 2 of cocos2d-obj (which was formerly called cocos2d-iphone). A ton of games still use this version.

**Comment by antoine-haas** [comment]
Hi @petriw and @RustyMoyher,

Are you still having issues when trying to compile your projects? The cocos2d coverage of the bridge should have increased by now.
