### ISSUE TITLE
Linker error (libCordova.lib;libSystem.lib;libiconv.lib;libzbar.lib) when porting an iOS app to UWP

### ISSUE THREAD

**Issue by Shagufta4786** [Microsoft/WinObjC#2759]
I am getting a linker error that says "cannot open input file "libCordova.lib"  and similar error for libSystem.lib, libiconv.lib and libzbar.lib.  ![linkererror](https://cloud.githubusercontent.com/assets/17315207/26818666/31294e74-4ab9-11e7-8ef2-0efc35c70672.PNG)

These libraries are listed among the additional dependencies in linker input in Visual Studio. If I remove these dependencies I get other 'Unresolved external error'. So it seems these libraries cant be ignored.
![unresolvederror](https://cloud.githubusercontent.com/assets/17315207/26818732/7c8f8194-4ab9-11e7-97cd-07c19fb97a87.PNG)

Does WinObjC not include these libraries at this point? Is there any way to get these library files or resolve this error. I searched for these files on Mac OS too but I could only find one libZbar.a file which I have no idea how to convert to .lib. 

Please help!!

**Comment by rajsesh-msft** [comment]
Hi @Shagufta4786 - some of these projects are available as open source projects (ex: libcordova, libiconv, libzbar).  I am not sure how many of these are available for windows.  libSystem is specific to Mac.  The winobjc bridge will not provide every library available in Mac.  Rather, it provides implementation for a subset of the iOS objc framework libraries that would allow you to port your app to windows.

Given that you are using cordova in your app, it probably makes sense to use cordova to target the app to windows rather than using the winobjc bridge.

**Comment by Shagufta4786** [comment]
Thank you @rajsesh-msft for your response. When you say, "use cordova to target the app to windows", you mean developing/writing a new app and not adapting/porting right? I understand this from this Microsoft doc [https://docs.microsoft.com/en-us/windows/uwp/porting/selecting-an-approach-to-ios-and-uwp-app-development]. I am asking to confirm as our purpose is to port the app and not write a new app.

**Comment by edvv** [comment]
@Shagufta4786 In your Xcode project's build phase take out the System library explicit dependency and see if your target links and runs. It is probably a relic from a long time ago. If so then use vsimporter on the result to aquire a solution without that dependency. The other libraries can be obtained on the web. If your hybrid app has a good ObjC/Cocoa Touch component then you might want to port using WinObjC, otherwise one can do a rewrite to a different technology depending on the needs.

**Comment by DHowett-MSFT** [comment]
Hi @Shagufta4786! Thanks for reporting this. I'm closing it out since it's a little stale and we aren't planning on supporting Cordova. Since it's a cross-platform technology already, it should be easier to bring over to windows that way.
Sorry!
