### ISSUE TITLE
cant access member variable from class inside a dll

### ISSUE THREAD

**Issue by arktouros** [Microsoft/WinObjC#2855]
I've made a dll for a project I'm working on 
with a class like
```
@interface customClass : NSObject {
@public float var1;
@public float var2;
}
- (float*) sum:(float) var1 :(float) var2
@end
```
and while I have access to the class selector, when i try to access the member variable 
from outside the dll, i get 
```
Exception thrown: read access violation.
___objc_ivar_offset_customClass.var1 was 0x420825FF
```
i've defined it in lib.def and exported the class in  the dll incude header
what do i have to do to have access to the variable

**Comment by DHowett-MSFT** [comment]
Hi @arktouros. Thanks for reporting this!
We've chosen to not allow access to ivars across module boundaries.
There's compiler work to be done to support importing and exporting them on Windows (due to some limitations of the PE/COFF object format), and we weighed that against the cost of exposing properties instead.

Sorry about that! If you have a compelling case for this that's not better-served by properties, I'll gladly reopen this.

**Comment by arktouros** [comment]
@DHowett-MSFT thanks for the quick answer, I wanted to avoid selectors or  properties, 
but if it's not supported I will have to go another way
