### ISSUE TITLE
UIBezierPath Not Found

### ISSUE THREAD

**Issue by TorreyBetts** [Microsoft/WinObjC#32]
This class should be ported as it's very useful for iOS controls that use CALayers or CoreGraphics.

**Comment by Baddaboo** [comment]
As much as I too really hope that this comes to WinObjC, I'm not sure how much the dev team would be able to on that, since UIBezierPath is just a wrapper for CoreGraphics, which is just a wrapper for Quartz, I believe. Quartz is closed and has many patents associated with it held by Apple, and a lot of the bezier techniques are patented and used by Adobe. So porting over these frameworks would be a pretty big legal feat before it's even a technical feat

**Comment by keluo-ms** [comment]
Good news! This was implemented with https://github.com/Microsoft/WinObjC/commit/81e211014f560491c74d4b8cc6b93f2bf7dc0f0b
