### ISSUE TITLE
_getSystemTZ in NSTimeZone is flawed, will return wrong time zone in many cases

### ISSUE THREAD

**Issue by mj1856** [Microsoft/WinObjC#328]
The [implementation of `_getSystemTZ`](https://github.com/Microsoft/WinObjC/blob/948bde3f1ad340727c50fdf380f8e61159c47328/Frameworks/UnifiedFoundation/Foundation/NSTimeZone.mm#L63-L108) in `NSTimeZone` is flawed in that attempts to match an IANA time zone to a Windows time zone based on the standard offset (from `timeZoneInfo.Bias`) and the locale's country code.  This is wrong for two reasons:

  1. Many time zones use the same base offset, but change to other offsets for daylight saving time, or for other reasons.  See "Time Zone != Offset" in [the timezone tag wiki on StackOverflow](http://stackoverflow.com/tags/timezone/info).

  2. The country code of a locale describes the user's preferred dialect of the language.  `en-US` means "English as spoken in the United States".  I may very well be an American *visiting* England - I would not switch to `en-GB` unless I had *moved* there and decided to pick up on local variations such as changing from `mm/dd/yyyy` to `dd/mm/yyyy` date formats.   The country code doesn't mean that's the country I'm physically located in, nor the one associated with the time zone setting of my computer.

The correct way to determine the system time zone on a Windows machine as an IANA identifier is to send the time zone id through [CLDR mappings](http://unicode.org/repos/cldr/trunk/common/supplemental/windowsZones.xml), which is actually already handled by ICU in the [`TimeZone::detectHostTimeZone`](http://icu-project.org/apiref/icu4c/classicu_1_1TimeZone.html#a5f820523041e38bff46f22567ef6cf86) method.  We should simply wrap that function and eliminate the custom logic in `_getSystemTZ`.

**Comment by mj1856** [comment]
Another method that would be acceptable is to call [`GetDynamicTimeZoneInformation`](https://msdn.microsoft.com/en-us/library/windows/desktop/ms724318.aspx) and then pass the `TimeZoneKeyName` from the resulting [`DYNAMIC_TIME_ZONE_INFORMATION`](https://msdn.microsoft.com/en-us/library/windows/desktop/ms724253.aspx) structure into the [`icu::TimeZone::getIDForWindowsID`](http://icu-project.org/apiref/icu4c/classicu_1_1TimeZone.html#a0872f72c5c3204de3c61502be568d72d) function.

**Comment by MSFTFox** [comment]
I've investigated this issue for quite some time, ever since the original NSTimeZone implementation was worked on. The bug primarily lied in our implementation of NSLocale where a particular method was incorrectly relying on the language code set by the user. This has since been updated.

Additionally, I want to say thank you for the suggestions in regards to more accurately retrieving the user's time zone information. Unfortunately not all of them are able to be used given some of the constraints we're working under. For example, the icu getIDForWindowsID function cannot be used at this time due to it only being available in newer version of ICU. This same issue affects the ICU default system time zone detection methods. We understand this problem and are working to correct it.

I'm happy to say we now correctly support daylight savings time and also support the correct region settings from the user to detect system time zone information. Our implementation is not yet perfect for all scenarios and we fully understand that. We have however taken measures to ensure that our system time zone implementation provides sufficient coverage for nearly all use cases.

Thank you again for your diligence on this issue.

**Comment by Ramu-msft** [comment]
The fix is available in 0.1 Preview (Mar 24, 2016) release.

**Comment by mj1856** [comment]
I reviewed the changes.  It's slightly better in that you take DST into consideration, but it's still going to give many mismatches.  Ultimately, the problem cannot be solved purely algorithmically - it needs access to the Windows zone mappings in CLDR, as exposed by ICU.

Could you at least use the `getIDForWindowsID` function in ICU 52?  Or is this project stuck on ICU 48?

**Comment by rajsesh-msft** [comment]
@mj1856 Thanks for the feedback.  Yes, this implementation is still fragile.  
We will move to ICU52 in the near future (we are waiting on another team porting it for UWP).  Once that is done, we will be able to use getIDForWindowsID.

**Comment by mj1856** [comment]
Understood.  Thanks!
