### ISSUE TITLE
Bridged Casting Not Supported

### ISSUE THREAD

**Issue by TorreyBetts** [Microsoft/WinObjC#33]
When you have code such as the following, should the __bridge cast be supported?

    CABasicAnimation *animation = [CABasicAnimation animationWithKeyPath:@"path"];
    animation.duration = _progressAnimationDuration;
    animation.timingFunction = [CAMediaTimingFunction functionWithName:_progressAnimationTimingFunction];
    animation.fromValue = (__bridge id) oldPath;
    animation.toValue = (__bridge id) path;
    [_progressShape addAnimation:animation forKey:@"animatePath"];

**Comment by jmsaunders-ms** [comment]
We haven't seen issues involving bridged casts. Are you positive you have ARC enabled?

How did you set your project up? Is it imported? (Perhaps ARC settings aren't being preserved) If it's just some code you added after enabling ObjC support in MSVC then you can enable ARC per-file or per-project in the settings dialog.

Can I get a compiler log of the error you're seeing?

**Comment by TorreyBetts** [comment]
I created a project this morning to demonstrate the issue. Also, this project was imported using vsimporter. Here's the VS log when attempting to build.

    1>------ Build started: Project: WinObjC_Issue33 (WinObjC_Issue33\WinObjC_Issue33), Configuration: Debug Win32 ------
    1>  ConsumeRuntimeComponent.cpp
    1>  ..\..\WinObjC_Issue33\main.m
    1>  ..\..\WinObjC_Issue33\AppDelegate.m
    1>  ..\..\WinObjC_Issue33\ViewController.m
    1>C:\winobjc\samples\WinObjC_Issue33\WinObjC_Issue33\ViewController.m(71,27): error : incompatible types casting 'CGPathRef' (aka 'id') to 'id' with a __bridge cast
    1>C:\winobjc\samples\WinObjC_Issue33\WinObjC_Issue33\ViewController.m(72,25): error : incompatible types casting 'CGPathRef' (aka 'id') to 'id' with a __bridge cast
    ========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
    ========== Deploy: 0 succeeded, 0 failed, 0 skipped ==========

Project can be downloaded here: https://www.dropbox.com/s/5hcvs7m6s15d4g9/WinObjC_Issue33.zip?dl=0

**Comment by jmsaunders-ms** [comment]
Thanks for the example.

The reason this is happening is because the iOS version of CGPathRef is a struct*, a C type. Our version is an id, which means no bridge cast is necessary in this circumstance (you can't bridge cast from id to id - in fact you don't have to).

This is a bug in our code. Unfortunately our CGPathRef _is_ an Objective C class called CGPath that has a few convenience methods on it. It should be a C struct with only state. This will be the case for some other Ref types as well (CGFont for example) but we've fixed up most of them already.

We're working on it! Sorry again.

**Comment by nicholasgerard-msft** [comment]
@TorreyBetts This issue should be fixed with newer versions of the bridge. Could you please check with [the latest release](https://github.com/Microsoft/WinObjC/releases) and close the issue if it is resolved?
