### ISSUE TITLE
Visual Studio Xib2Nib Error after Converting iOS 9.2 Project

### ISSUE THREAD

**Issue by mbcrump** [Microsoft/WinObjC#367]
The project runs properly through vsimporter. Once opened in Visual Studio, it produces the following error : 

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3073	The command ""C:\Users\micrum\Downloads\winobjc\msvc\..\bin\Xib2Nib.exe" "..\..\WindowsBridgeTestTemplate\Base.lproj\Main.storyboard" "Debug\Base.lproj\Main.storyboardc"" exited with code -1.	WindowsBridgeTestTemplate (WindowsBridgeTestTemplate\WindowsBridgeTestTemplate)	C:\Users\micrum\Downloads\winobjc\msvc\sbresources.targets	167	

```
If I try running the project again, it will move past this error and only display a black screen. The template for the project is located below.
 
[WindowsBridgeTestTemplate.zip](https://github.com/Microsoft/WinObjC/files/145451/WindowsBridgeTestTemplate.zip)

**Comment by decademoon** [comment]
+1

**Comment by segadude** [comment]
I'm having the same issue.

**Comment by Ramu-msft** [comment]
The WindowsBridgeTestTemplate application seems to be using a class which is not supported by our framework. Are you using UIStackView in your application?

**Comment by Ramu-msft** [comment]
I have verified that the app is using UIStackView. Currently we do not have support for this. Since this is not supported, the xib2nib tool fails while processing the storyboard. You can see this in the build log.
1>         Unable to find class mapping for required object <stackView>

We will add this to our backlog. Please consider using a view that is supported by our SDK.
