### ISSUE TITLE
unknown argument: '-fvisibility=default'

### ISSUE THREAD

**Issue by mohamednossair** [Microsoft/WinObjC#409]
Severity	Code	Description	Project	File	Line	Column	Suppression State
Error		unknown argument: '-fvisibility=default'	OsiriX API (Legacy)	C:\horos-horos\Horos.vsimporter\OsiriX API (Legacy)-WinStore10\CLANG	1	1

**Comment by ArnOmsft** [comment]
Could you please provide more info about this: are you getting this error when running VSImporter or at compile time?
Thanks.

**Comment by mohamednossair** [comment]
at the compile time

**Comment by ArnOmsft** [comment]
Thanks. So you imported your iOS app as a Visual Studio solution with no problem and you're getting this error when build your app in Visual Studio.
Which version of our SDK are you using?
Which version of Windows 10 are you using (OS build version you can find in Settings/System/About)?
Which version of Visual Studio are you using?

**Comment by ArnOmsft** [comment]
Also did you submit your IPA on https://developer.microsoft.com/en-us/windows/bridges/ios/app-submission so we could try to repro? Thanks.

**Comment by asimonov-msft** [comment]
@mohamednossair This happens because we do not invoke clang using the standard driver, but rather with clang -cc1.

You can try removing the offending argument. It should be under "Clang -> Command Line -> Additional Options". Alternatively, you can try replacing it with "-fvisibility default" (without the quotes).

**Comment by s5msft** [comment]
Closing this as a dup of #426
