### ISSUE TITLE
NSKeyedUnarchiver of NSDate objects not working.

### ISSUE THREAD

**Issue by rupertdaniel** [Microsoft/WinObjC#413]
Implement [NSDate encodeWithCoder:] so that NSDate instances can be serialised using NSCoding.

**Comment by DHowett-MSFT** [comment]
NSDate is one of the basic property list serializable types and should serialize naturally through encodeObject:forKey:.



On Fri, Apr 1, 2016 at 2:31 AM -0700, "Rupert Daniel" <notifications@github.com<mailto:notifications@github.com>> wrote:


Implement [NSDate encodeWithCoder:] so that NSDate instances can be serialised using NSCoding.

-

**Comment by rupertdaniel** [comment]
Ahh ok. Actually I think the issue I'm seeing is with unarchiving.

When NSKeyedUnarchiver is unarchiving the NSDate object, the following line `result = [result initWithCoder:self];` returns nil and it throws an exception.

https://github.com/Microsoft/WinObjC/blob/master/Frameworks/UnifiedFoundation/Foundation/NSKeyedUnarchiver.mm#L215

**Comment by rajsesh-msft** [comment]
@jofre-ms is taking this now.
