### ISSUE TITLE
How are libraries handled by vsimporter?

### ISSUE THREAD

**Issue by joewood** [Microsoft/WinObjC#42]
When I run vsimporter on a project with libraries, the resulting solution has a single Windows Store app, the dependent libraries in all one solution. That's great.
But I'm a little confused about the conversion process. The libraries are set-up as .lib outputs, but the main executable has a reference to them as assemblies.  
The problem is that the solution won't compile the dependent libraries. I'm seeing errors about missing .tlh files - which it seems to expect to see for each `#import`.

Are libraries supported at the moment?

**Comment by asimonov-msft** [comment]
The .tlh errors come from IntelliSense because it doesn't yet understand Objective C. These errors should not cause compilation problems, but we will leave the issue open as a reminder about the IntelliSense problem.

The main executable project references the static library projects as assemblies, but Visual Studio will realize the outputs are static libs and should simply link against them. If this is not working for you, could you provide us with the build/link errors that you're seeing?

**Comment by keluo-ms** [comment]
Our team is now using Issue #40 to track getting IntelliSense working.
