### ISSUE TITLE
vsimporter.exe

### ISSUE THREAD

**Issue by kemalserkan** [Microsoft/WinObjC#460]
Unsupported 16-Bit Application

The program or feature "...\WinObjC-master\bin\vsimporter.exe" cannot start or run due to incompatibitiy with 64-bit versions of Windows. Please contact the software vendor to ask if a 64-bit Windows compatible version is available.

What can I do for this error?  Please help me ?

**Comment by rajsesh-msft** [comment]
@kemalserkan are you using the zipfile to download the sources?  Please make sure you have GitLFS installed as noted in readme.md

Note on installing the bridge: We've switched to using Git LFS to handle the large binaries included in the bridge. This does not affect using the prebuilt releases found on our releases page, but if you build the bridge from source, please see the instructions found on our Building From Source wiki page.

Please do not use the "Download ZIP" button above, since you will not be able to build the bridge using the resulting .zip file. For more information on why this is the case, see "I'm getting errors after downloading the bridge through the "Download ZIP" button on Github. What should I do?" in our FAQ.

**Comment by rajsesh-msft** [comment]
@kemalserkan please reopen if you still see this after using git-lfs.
