### ISSUE TITLE
NSCache implementation missing

### ISSUE THREAD

**Issue by triplef** [Microsoft/WinObjC#476]
NSCache is currently unimplemented.

**Comment by RG-J** [comment]
If its okay, I'll go ahead with the implementation.
R

**Comment by rajsesh-msft** [comment]
@RG-J Thanks so much for offering.  Will let you know by end of day.

**Comment by rajsesh-msft** [comment]
@RG-J this is urgently required to unblock a customer, so we will do this one internally.  If you are interested, i could tag you on a few issues where we can use your help.  Thanks again for your contributions!

**Comment by DHowett-MSFT** [comment]
Since the reference documentation imposes no restrictions on the backing store for NSCache, apart from that it bear dictionary semantics, we have a bit of agency in how we implement it. I intend to start with a simple LRU cache.

### Details

Using a doubly-linked list (for quick element replacement and removal) and a hash table (for quick lookups) seems like it will be the right choice here. Since we're a primarily C++-on-the-inside codebase, we'll use `std::list<_NSCacheEntry>` and `std::unordered_map<id, std::list<_NSCacheEntry>::iterator>`, with specializations for `std::hash<id>` and `std::equal_to<id>`.

`std::list` was chosen for its stable iterators and efficient reverse traversal. We'll keep the cost on `_NSCacheEntry`, even if there is no cost.

### Operations

#### Insertion - O(1) amortized

* Prepend a new cache entry `{key, value, cost}` to the _backing list_.
* Insert a new entry mapping `key` to the _iterator hash table_.
* Evict all objects over the cache limit -- including, possibly, the newly-added one.

#### Removal - O(1) amortized

* Find the iterator corresponding to `key`.
* Remove the iterator from the backing list.
* Remove the found iterator from the _iterator hash table_.

#### Lookup - O(1)

* Find the iterator corresponding to `key`.
* Promote it to the head of the _backing list_.

#### Eviction/Cost Balancing - O(n) worst case

* Starting at the end of the _backing list_, remove items.
  * If we have a cost limit, only remove items with a nonzero cost.
  * If we have a count limit, remove items regardless of their costs.
  * If we have both, remove items following the above rules until both limits are met.

Eviction is the only `O(n)` operation for the LRU cache: in the worst case, we must remove every item from the _backing list_. With sane defaults, we shouldn't hit the pathological case.

### Compatibility

**NSDiscardableContent** objects will be discarded during eviction, but only removed from the cache if `evictsObjectsWithDiscardedContent` is enabled. If they are not evicted, they will be considered to have `0` cost.
