### ISSUE TITLE
Suggestion - publish a roadmap

### ISSUE THREAD

**Issue by joewood** [Microsoft/WinObjC#48]
It would be great if you could publish a roadmap, what's a priority for the team and what areas you're looking for the community to contribute.
The model used by the TypeScript team (and others) seems to work well, where GH issues are tagged as "accepting PRs" and a roadmap is published and kept to the date.

**Comment by sirinath** [comment]
+1

**Comment by IvanKarpan** [comment]
+1, definitely

**Comment by IvanKarpan** [comment]
Found this, probably the list is prioritize:
https://github.com/Microsoft/WinObjC/wiki#whats-still-under-development

**Comment by YusukeYamamoto** [comment]
+1, we don't know where we are now, where we are going now.
The roadmap will be help for us to contribute it and to discuss it.

**Comment by s5msft** [comment]
This is a great suggestion. Two part answer:

> we don't know where we are now

We’re building out a test framework that, along with some visualization, should provide a decent sense of what works and what doesn’t. The (basic) test framework should be in place this/next week, with the visualization stuff still being built out (so that’ll take a bit longer). And, of course, the framework will need to be properly populated with tests, which will be an ongoing process.

> It would be great if you could publish a roadmap

Priorities are largely influenced by apps, partners, and feedback received here. But (per the above comment) this lists the “big picture” priorities: https://github.com/Microsoft/WinObjC/wiki#whats-still-under-development

Additionally, going forward we’ll mark issues appropriately to denote that they're "in progress" to give you a sense of what’s coming in the near/medium term.

**Comment by joewood** [comment]
That's good to know. A visualization of the gaps would be useful. 
What about the issue of community contribution? Right now it's hard to know where contributions can be made without the risk of working on something that is already being developed by the MS team. Can the issues be labeled if there are no plans to add a specific feature?

**Comment by s5msft** [comment]
@joewood if an issue is unassigned then you're free to run with it

**Comment by technotrance** [comment]
All sounds good but we need a picture of a layout map

**Comment by nicholasgerard** [comment]
We're working on web tools to provide exactly this functionality – you'll be able to see what's supported now, what we're working on and even upload your app for a fast analysis of how compatible with the iOS bridge it is. However, we need IPAs to test our pipeline out with, so if you want to support the project, we're accepting submissions here:

https://dev.windows.com/bridges/ios/app-submission

Stay tuned!

**Comment by nicholasgerard-msft** [comment]
Check out the new and improved Wiki for a high-level view of what we're working on:

https://github.com/Microsoft/WinObjC/wiki

**Comment by joewood** [comment]
That's great. Just a suggestion - it would be useful to annotate the features with future prospective version numbers like the TypeScript team do. Although this may be tentative, it's a good way of understanding relative priorities and complexity.
