### ISSUE TITLE
KVO events not generated for all defined keyPaths in keyPathsForValuesAffecting<X>

### ISSUE THREAD

**Issue by rupertdaniel** [Microsoft/WinObjC#500]
KVO events are not generated when changes are made to all defined keyPaths in `keyPathsForValuesAffecting<X>`.

Attached is a sample application that demonstrates the issue.

1. Unzip demo app, build and run.
2. Press button "Update Name Property"

This action updates the two keyPaths defined in `keyPathsForValuesAffectingValid` in TestObject.m. KVO events should be triggered for both updates so that the property `valid` eventually returns `YES`, but at the moment this is not happening.

[KVOBug-affectedKeyPaths.zip](https://github.com/Microsoft/WinObjC/files/268297/KVOBug-affectedKeyPaths.zip)

**Comment by DHowett-MSFT** [comment]
Got a root cause and a potential fix for this one.
When we are tearing down stale observers and reconstructing new ones (for descendent keypaths), we were erroneously not doing so if we were in the middle of a change notification for the same keypath.

That is: changing `childObject` triggered the two sub-observers, `childObject.name` and `childObject.value` to fire (which is correct), but when we were rebuilding the keys, we skipped `childObject.name` because we were already dispatching a notification.

Fix: Reconstruct keypaths regardless of whether/not we're currently notifying. This is objectively more correct.

**Comment by DHowett-MSFT** [comment]
This was fixed some time ago.
