### ISSUE TITLE
Save As Image Option

### ISSUE THREAD

**Issue by SivaguruElangovan** [Microsoft/WinObjC#506]
Save as image options works as intended on iOS and saves image to Photos, but does not work on Windows even after including required permissions.
Sample project link:  https://github.com/SivaguruElangovan/WinObjC-CH-Sample

**Comment by nicholasgerard-msft** [comment]
Could you elaborate on what you're trying to achieve and what APIs you're using? The sample project you linked to contains an unused DrawingView class, but since it's not used anywhere I'm unclear on your use case and on what, exactly, isn't working. Are you trying to render a UIView to a UIImage, or save an image to disk?

**Comment by cre8ivepark** [comment]
I have same issue on saving image to the photos album(camera roll)
It looks like this API is not implemented yet.

**UIImageWriteToSavedPhotosAlbum**(viewImage, self,
                                   @selector(image:didFinishSavingWithError:contextInfo:),
                                   nil);

**Comment by ArnOmsft** [comment]
Correct, this specific API UIImageWriteToSavedPhotosAlbum is currently stubbed. I'll check what amount of work is required here.

**Comment by tadam-msft** [comment]
See recommendation in #2162
