### ISSUE TITLE
Crash when replacing/removing item in NSCache.

### ISSUE THREAD

**Issue by rupertdaniel** [Microsoft/WinObjC#519]
If you set an object in NSCache using a dynamically created key e.g. `[NSString stringWithFormat:@"key-%d", 1]`, when you replace or remove the object from the cache it crashes at line NSCache.mm:57.

Below is some example code that triggers the crash:

```
self.cache = [[NSCache alloc] init];

[self.cache setObject:[[UIImage alloc] init] forKey:[NSString stringWithFormat:@"key-%d", 0]];

dispatch_async(dispatch_get_main_queue(), ^{
	[self.cache setObject:[[UIImage alloc] init] forKey:@"key-0"];
});
```

**Comment by DHowett** [comment]
@rupertdaniel thanks for the report;
Does the backtrace run through line [262](https://github.com/Microsoft/WinObjC/blob/f67a1f63fac577367fbd5fe172930ad3a502b7b4/Frameworks/Foundation/NSCache.mm#L262) as well?
I wonder if `std::map` will re-hash on `erase(iterator&)`?
If so, `key` is dead by then, and `[key hash]` would almost certainly be a bad thing to do.
A quick fix might be to rearrange 262 above 261, so that the last release happens after the last use.

**Comment by rupertdaniel** [comment]
Yeah it does run through line 262, attached is a screenshot of the stack trace.

I've tried swapping lines 262 & 261, but it still crashes.

<img width="689" alt="screenshot 2016-05-28 06 55 00" src="https://cloud.githubusercontent.com/assets/237035/15625548/368df920-24a2-11e6-9c87-6af96269ed5f.png">
