### ISSUE TITLE
Removing a KV observer stops other KV observers from firing.

### ISSUE THREAD

**Issue by rupertdaniel** [Microsoft/WinObjC#531]
Removing a KV observer prevents other KV observers registered for the same object & keyPath from firing.

General steps to reproduce:

1. Add observer1 to object A + keyPath X
2. Add observer2 to object A + keyPath X
3. Remove observer2
4. Update observed property at keyPath X.

Observer1 does not get the change event that should be generated by step 4.

Attached is a demo project that illustrates the issue.

1. Download, build and run.
2. Click the "Update Name Property" button

It should log out "Changed!!", but by removing the second observer, the first observer no longer receives change events.

[KVOBug-remove.zip](https://github.com/Microsoft/WinObjC/files/298239/KVOBug-remove.zip)

**Comment by DHowett-MSFT** [comment]
Root cause: The removal check at [NSKVOSupport.mm:377](https://github.com/Microsoft/WinObjC/blob/master/Frameworks/Foundation/NSKVOSupport.mm#L377) doesn't check whether the observers match before removal.

Our tests failed to catch this because they remove the observers in creation order -- so the second observer would still fire notifications.
