### ISSUE TITLE
Define a code style to follow for all sources

### ISSUE THREAD

**Issue by vmagaziy** [Microsoft/WinObjC#54]
Right now it seems there are no conventions for code style. Different sources are formatted differently, it order to have a coherent look for all sources it' proposed to choose of the options:

1) [LLVM] (http://llvm.org/docs/CodingStandards.html)
2) [Google] (http://google.github.io/styleguide/objcguide.xml)
3) [Chromium] (https://www.chromium.org/developers/coding-style)
4) [Mozilla] (https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Coding_Style
5) [WebKit] (https://www.webkit.org/coding/coding-style.html)

and follow them by using git pre-commit hooks driven by [clang-format] (http://clang.llvm.org/docs/ClangFormat.html). The styles from the list are supported out of the box.

I have an experience with setting this infrastructure up, so I am ready to proceed with re-formatting and adding the mentioned hooks. What I need is the decision which code style is to use.

**Comment by jmsaunders-ms** [comment]
Partial +1

I'm all for using clang-format and have been pushing a bit to have that done. I'd specifically not use the LLVM style though since VariableNames look strange to me. Further, we make (imo) good use of exceptions in some of our tools, which goes against some of the style guides.

I'd prefer I think to base it on the Google style guide with some modifications. This is likely coming but I wouldn't expect it this week. It's a bit prickly because none of them are specifically Objective C style guides and that's the majority of  our code.

More on this later.

**Comment by vmagaziy** [comment]
@jmsaunders-ms thanks for your answer and support of this idea, can you please have a look at [PL](https://github.com/Microsoft/WinObjC/pull/70) with initial changes related to this issue?

**Comment by vmagaziy** [comment]
@s5msft, please close this issue or mark it as addressed by your team, otherwise someone else may decide to make the same mistake I did with my **PL**.

**Comment by nicholasgerard-msft** [comment]
We've now published coding guidelines and standards as part of our wiki. Please take a look at [How to Contribute](https://github.com/Microsoft/WinObjC/wiki/How-to-Contribute) and [ClangFormat](https://github.com/Microsoft/WinObjC/wiki/ClangFormat) for more information. Thanks!
