### ISSUE TITLE
NSUserDefaults are not being saved across launches

### ISSUE THREAD

**Issue by triplef** [Microsoft/WinObjC#583]
User defaults settings are not being restored when re-launching the app.

Running the following code should output `Test value: 0` the first time, but `Test value: 1` for every subsequent run of the app. However, it always outputs `Test value: 0`.

```objc
NSLog(@"Test value: %d", [[NSUserDefaults standardUserDefaults] boolForKey:@"Test"]);
[[NSUserDefaults standardUserDefaults] setBool:YES forKey:@"Test"];
```

**Comment by rajsesh-msft** [comment]
I got a repro of this.  The issue here is that our test app is calling synchronize after writing the value, so it is getting persisted.  The API doesn't require synchronize to be called, iOS does that automatically periodically.  

Since we don't have a preferences service running to sync the data periodically, we should add a periodic synchronization somewhere.  you can workaround by calling synchronize manually.

**Comment by triplef** [comment]
Thanks @rajsesh-msft for taking another look at this and for the workaround!

**Comment by LeoNatan** [comment]
Apple persists the user defaults not "periodically" but in key points of application lifetime, such as application moving to background, inactive, before termination, etc. All these can be achieved in the bridge as well.
