### ISSUE TITLE
Roadmap for CoreFoundation/Foundation implementation

### ISSUE THREAD

**Issue by vmagaziy** [Microsoft/WinObjC#60]
It has to define the approach for implementation of toll-free bridging for CoreFoundation/Foundation, namely whether CoreFoundation is implemented using Foundation or vice versa. In order to simplify the further support of KVO/KVC via CoreFoundation calls it's easier to opt for the first variant, but it has to be defined at least and it has to follow the same approach thought all entities.

**Comment by vmagaziy** [comment]
@s5msft, in issue #8 you stated that current implementation of WinObjC is not correct. Can you please confirm the *CoreFoundation* framework will be implemented via the *Foundation* framework in contradiction to the Apple's approach?

**Comment by lhoward** [comment]
Agreed – see also issue #83. Implementing CoreFoundation in Objective-C is fine (this is now the case for some of the Apple implementation), but particular care does need to be taken if one is implementing CoreFoundation on top of Foundation.

**Comment by rajsesh-msft** [comment]
We have several known issues particularly with bridging and support for polymorphism on collections.  Our current plan is to bring in the Apple Core Foundation implementation, and switch foundation to use the new CF.  Expect this to land sometime in the next couple of month or sooner.

**Comment by rajsesh-msft** [comment]
Further update on this. Since this issue is asking about how we are doing this:
1. We are filling out core foundation from the apple corefoundation project.  This work is expected to land soon.
2. The Foundation classes that do need to be bridged will be bridged with CF and use as much code as possible from CF.

We won't be 100% in this model specifically for cases where we have an NS implementation (example NSBundle), but we do plan to migrate all of this over.

@bbowman will publish a design document on the bridging when this work comes out.

Closing this out for now.
