### ISSUE TITLE
STUB_PROPERTY and STUB_METHOD

### ISSUE THREAD

**Issue by jaimerodriguez** [Microsoft/WinObjC#601]
Is everything that is flagged as STUB* deprecated ? or  some might be implemented later? 

The warning often says "deprecated: property not yet implemented".  
This is not useful in telling me if it will be coming later and I should wait for it, or it is deprecated and I should 'implement or workaround'..  Is there a way to tell the difference?

**Comment by msft-Jeyaram** [comment]
STUB_* are entities that are not yet implemented (/to be implemented in the future)
I can see that for STUB_* properties and methods in UIKit project, it's indicating it's deprecated, @asimonov-msft  could shed more light into why we are getting **deprecated** tags for the warning.

**Comment by rajsesh-msft** [comment]
https://github.com/Microsoft/WinObjC/wiki/FAQ#whats-the-deal-with-all-of-these-stubs has the details about stubs.  The warning says deprecated because we use deprecated() attribute (we needed a reliable attribute) to tag them.

We have stubs to enable most apps to compile easily.  The idea here is that the app will be functional for key scenarios with just the stubs.  

Stub doesnt mean we will implement something in the future.  If you need some stubbed method, please do open an issue for what you need.  Alternatively, we would appreciate pull requests as well.  Hope that helps.

**Comment by rajsesh-msft** [comment]
@jaimerodriguez closing this issue for now, please let us know if you have any other questions on this.
