### ISSUE TITLE
CFUUID is not implemented

### ISSUE THREAD

**Issue by colemancda** [Microsoft/WinObjC#7]
The implemented methods only declare assertions thats will always fail.

**Comment by jmsaunders-ms** [comment]
Yeah we have no implementation of this for the time-being because we have no apps that function as test-cases for them.

If you're interested in implementing it, there will be a testing suite available fairly soon that we can use to validate it with, after writing some simple tests for it.

Sorry for the delay in answering.

**Comment by jofre-ms** [comment]
The fix for this is written, tested, and going in soon.
