### ISSUE TITLE
Investigate root cause for significant time consumed by loader 

### ISSUE THREAD

**Issue by rajsesh-msft** [Microsoft/WinObjC#715]

**Comment by bbowman** [comment]
After investigation it appears that I was incorrect in my initial analysis. It is not the loader itself that is causing the delay. This was a mistake when reading the trace. For the sample app, the time is broken down as follows:

154.6 ms total startup thread time
| - 129.82 ms  - GetActivationFactory (runtime setup time)
|          | - 108.7 ms - Framework CRT init (objc static init) <----- BIG HITTER
|          | - 21.14 ms - Loader, Interop, etc. (mostly fixed cost overhead)
| - 24.29 ms - ActivateInstance (actual business logic time)

The differences seen in different investigations was likely just due to differing environments / surrounding conditions not actual savings. My mistake for misreading the traces (was confused because it broke down the framework init calls into several different sections underneath identical loader calls that made it hard to find them all). This suggests that the work to defer selector registration etc will be more valuable than initially expected and probably worth the risks.
