### ISSUE TITLE
performSelector, NSInvocation, etc likely should use objc_msgSend

### ISSUE THREAD

**Issue by lhoward** [Microsoft/WinObjC#79]
I'm not privy to the objc_msgSend implementation but comparing to Apple's implementation, -[NSObject performSelector:], NSInvocation, etc, should probably call objc_msgSend to take advantage of selector caching and also to support the nil receiver.

**Comment by jmsaunders-ms** [comment]
I wanted to clear a few things up about this.

First, we have no objc_msgSend. This is because we're targeting the ObjFW runtime code generation style (controlled by -fobjc-runtime=objfw in sbclang.props). This means the compiler emits code using objc_msg_lookup, which returns the function pointer for the method in question. objc_msg_lookup has some magic to do fast lookups that we haven't had performance problems with (yet).

I think the performSelector code is ok because it returns an id. The reason NSInvocation is horrifying at the moment is because it needs to handle calling convention weirdness. For instance, we need to recognize when the method invocation is returning a floating point value and call the function pointer as that, otherwise we won't get the correct return value! Same story with structs, with some special cases. Unless I'm misunderstanding something, I don't think the performSelector code can share anything real with NSInvocation.

That said, there may be an issue with nil receivers in NSInvocation. If this is the case we should open a separate bug report for that.

**Comment by lhoward** [comment]
Ah, OK, didn't realise it wasn't using the Apple ABI. Makes sense.

**Comment by lhoward** [comment]
One question though – how does performSelector/invoke interact with message forwarding if it avoids calling objc_msg_lookup()?

**Comment by jmsaunders-ms** [comment]
You're right that forwardInvocation isn't currently supported. It's on our radar. :)
